### ISSUE TITLE
Uncaught Error: listen EADDRINUSE :::54000

### ISSUE THREAD

**Issue by jesseminn** [livestyle/atom#2] opened 2016-01-03 19:06 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [livestyle-atom](https://github.com/livestyle/atom) package, v0.1.1
### Stack Trace

Uncaught Error: listen EADDRINUSE :::54000

```
At events.js:141

Error: listen EADDRINUSE :::54000
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at module.exports (/Users/JC/.atom/packages/livestyle-atom/lib/server.js:32:9)
    at WebSocket.<anonymous> (/Users/JC/.atom/packages/livestyle-atom/lib/client.js:54:12)
    at WebSocket.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at WebSocket.emit (events.js:169:7)
    at ClientRequest.onerror (/Users/JC/.atom/packages/livestyle-atom/node_modules/ws/lib/WebSocket.js:686:10)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1250:8)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "preview-plus",
      "tool-bar",
      "tool-bar-main",
      "atom-terminal",
      "swackets"
    ],
    "themes": [
      "atom-material-ui",
      "an-old-hope-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
an-old-hope-syntax, v0.4.1
atom-html-preview, v0.1.13
atom-material-ui, v0.8.0
autoclose-html, v0.19.0
autocomplete-paths, v1.0.2
bezier-curve-editor, v0.7.2
color-picker, v2.0.14
emmet, v2.3.17
file-icons, v1.6.13
highlight-column, v0.5.0
highlight-line, v0.11.0
highlight-selected, v0.11.1
jshint, v1.8.3
linter, v1.11.3
linter-csslint, v1.1.0
linter-htmlhint, v0.2.2
livestyle-atom, v0.1.1
minimap, v4.19.0
minimap-bookmarks, v0.2.0
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
pigments, v0.19.5
project-manager, v2.6.5
sync-settings, v0.6.0
trailing-spaces, v0.3.2
vim-mode, v0.64.0

# Dev
No dev packages
```

**Comment by sergeche** [comment] 2016-01-03 19:10
Do you have opened Sublime Tex with LiveStyle plugin installed?

**Comment by jesseminn** [comment] 2016-01-04 16:12
Yes. I have both atom and sublime text installed livestyle, but I didnt opened sublime text when this issue happened to atom.

**Comment by sergeche** [comment] 2016-01-04 16:41
If you open http://127.0.0.1:54000 in browser, what do you see?

**Comment by jesseminn** [comment] 2016-01-04 18:38
LiveStyle WebSocket server is up and running by Atom plugin.

**Comment by sergeche** [comment] 2016-01-04 18:40
Hmm, seems like everything works fine now?

**Comment by jesseminn** [comment] 2016-01-04 18:44
everything works fine even I got that error message, it's just a little bit annoying...maybe that's because sometimes I run sublime text & atom in the same time.

**Comment by sergeche** [comment] 2016-01-04 18:45
Yes, that might be the issue. Looks like you have outdated LiveStyle plugin in Sublime Tex. It doesn’t support shared web-server. You should update ST plugin to get rid of this issue

**Comment by jesseminn** [comment] 2016-01-04 18:56
Updated livestyle in sublime, have both atom and sublime run in the same time, and no error message pops out. Thanks for help!

**Comment by jesseminn** [comment] 2016-01-04 19:10
sorry, error message still pops out in atom, but livestyle works fine.

**Comment by sergeche** [comment] 2016-01-04 19:12
That’s weird. Will try to figure out what’s going on there. Do you reload Atom somehow or you completely restart it?

**Comment by jesseminn** [comment] 2016-01-04 19:25
I both restart sublime and atom, after couple of minutes the error message pops out.

**Comment by sergeche** [comment] 2016-01-18 12:09
Was able to reproduce this issue: happens if Atom starts with multiple windows or if one window in Dev Mode. Seems like Atom creates new plugin instance

**Comment by Haprog** [comment] 2016-02-27 21:33
I just installed livestyle for both Sublime and Atom. I had both running at the same time, but I got this error for the first time on Atom right when I quit Sublime.

**Comment by DigiSquid** [comment] 2016-03-07 20:43
On LiveStyle for Atom and get the same error at startup. Don't use Sublime, however, so I don't think it's related to that. Here's a stack trace:

Error: listen EADDRINUSE :::54000
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at module.exports (/Users/me/.atom/packages/livestyle-atom/lib/server.js:32:9)
    at WebSocket.<anonymous> (/Users/me/.atom/packages/livestyle-atom/lib/client.js:54:12)
    at WebSocket.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at WebSocket.emit (events.js:169:7)
    at ClientRequest.onerror (/Users/me/.atom/packages/livestyle-atom/node_modules/ws/lib/WebSocket.js:686:10)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1250:8)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

**Comment by sergeche** [comment] 2016-07-13 14:23
Should be fixed in v0.2

**Closed as completed by sergeche** 2016-07-13 14:23 UTC

**Comment by smlombardi** [comment] 2016-08-31 13:59
This just happened again with 1.10beta 7 and 0.2.7.  It happened after I updated linter-stylelint to 3.2.1

**Comment by biroplane** [comment] 2017-01-05 11:48
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.9
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [node-resolver](git://github.com/hughsk/atom-node-resolver) package, v1.0.1


### Stack Trace

Failed to activate the node-resolver package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.exports.activate (/Users/gaetano/.atom/packages/node-resolver/index.js:12:21)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:184:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:157:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:550:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:508:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:792:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited",
    "useCustomTitleBar": true
  }
}
```

### Installed Packages

```coffee
# User
ariake-dark-syntax, v0.0.6 (inactive)
atom-bootstrap3, v1.2.12 (inactive)
atom-clock, v0.1.2 (inactive)
atom-electron-snippets, v2.0.3 (inactive)
atom-fontawesome, v0.2.0 (inactive)
autocomplete-json, v5.2.0 (inactive)
autoprefixer, v3.6.0 (inactive)
emmet, v2.4.3 (inactive)
file-icons, v2.0.7 (inactive)
font-viewer, v0.3.1 (inactive)
linter, v1.11.18 (inactive)
linter-sass-lint, v1.7.4 (inactive)
livestyle-atom, v0.2.7 (inactive)
node-debugger, v1.9.2 (inactive)
node-resolver, v1.0.1 (inactive)
nodejs-snippets, v2.0.2 (inactive)
qolor, v0.4.1 (inactive)
sass-autocompile, v0.13.2 (inactive)
scss-media-queries, v0.4.0 (inactive)
scss-snippets, v0.6.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.13.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.4 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.2 (inactive)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.4 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.2 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.0 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```
