### ISSUE TITLE
Deprecated selector in `livestyle-atom/styles/widgets.less`

### ISSUE THREAD

**Issue by PixelT** [livestyle/atom#18] opened 2017-01-11 09:01 UTC
In `livestyle-atom/styles/widgets.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .gutter-shadow` => `atom-text-editor.editor .gutter-shadow`

* `atom-text-editor::shadow livestyle-widget` => `atom-text-editor.editor livestyle-widget`

* `atom-text-editor::shadow livestyle-widget::before` => `atom-text-editor.editor livestyle-widget::before`

* `atom-text-editor::shadow livestyle-widget::before` => `atom-text-editor.editor livestyle-widget::before`

* `atom-text-editor::shadow livestyle-widget[position*="top"]` => `atom-text-editor.editor livestyle-widget[position*="top"]`

* `atom-text-editor::shadow livestyle-widget[position*="top"]::before` => `atom-text-editor.editor livestyle-widget[position*="top"]::before`

* `atom-text-editor::shadow livestyle-widget[name="selector"]` => `atom-text-editor.editor livestyle-widget[name="selector"]`

* `atom-text-editor::shadow livestyle-widget[name="selector"]::before` => `atom-text-editor.editor livestyle-widget[name="selector"]::before`

* `atom-text-editor::shadow livestyle-widget[name="variable-suggest"]` => `atom-text-editor.editor livestyle-widget[name="variable-suggest"]`

* `atom-text-editor::shadow livestyle-widget[name="variable-suggest"]::before` => `atom-text-editor.editor livestyle-widget[name="variable-suggest"]::before`

* `.theme-atom-material-ui atom-text-editor::shadow livestyle-widget:not([name=variable-suggest])` => `.theme-atom-material-ui atom-text-editor.editor livestyle-widget:not([name=variable-suggest])`

* `.theme-atom-material-ui atom-text-editor::shadow livestyle-widget[name=variable-suggest]` => `.theme-atom-material-ui atom-text-editor.editor livestyle-widget[name=variable-suggest]`

* `atom-text-editor::shadow livestyle-color-preview` => `atom-text-editor.editor livestyle-color-preview`

* `atom-text-editor::shadow livestyle-color-preview[approximate]::before` => `atom-text-editor.editor livestyle-color-preview[approximate]::before`

* `atom-text-editor::shadow .livestyle-variable-suggest__title` => `atom-text-editor.editor .livestyle-variable-suggest__title`

* `atom-text-editor::shadow .livestyle-variable-suggest__item` => `atom-text-editor.editor .livestyle-variable-suggest__item`

* `atom-text-editor::shadow .livestyle-variable-suggest__item:hover` => `atom-text-editor.editor .livestyle-variable-suggest__item:hover`

* `atom-text-editor::shadow .livestyle-variable-suggest__item:last-child` => `atom-text-editor.editor .livestyle-variable-suggest__item:last-child`

* `atom-text-editor::shadow .livestyle-variable-suggest__varname` => `atom-text-editor.editor .livestyle-variable-suggest__varname`

* `atom-text-editor::shadow .livestyle-variable-suggest__varvalue` => `atom-text-editor.editor .livestyle-variable-suggest__varvalue`

* `atom-text-editor::shadow .livestyle-mixin__hl > .region::before` => `atom-text-editor.editor .livestyle-mixin__hl > .region::before`

* `atom-text-editor::shadow .livestyle-mixin__hl_expanded > .region::before` => `atom-text-editor.editor .livestyle-mixin__hl_expanded > .region::before`

* `atom-text-editor::shadow .livestyle-hyperlink_hover .region` => `atom-text-editor.editor .livestyle-hyperlink_hover .region`

* `atom-text-editor::shadow .livestyle-value-with-suggest .region` => `atom-text-editor.editor .livestyle-value-with-suggest .region`

* `atom-text-editor::shadow .livestyle-value-with-suggest.livestyle-hyperlink_hover .region` => `atom-text-editor.editor .livestyle-value-with-suggest.livestyle-hyperlink_hover .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by omarciovsena** [comment] 2017-01-18 22:28
It is also available to me after I updated the atom to version 1.13.0

**Comment by mstashev** [comment] 2017-03-08 17:34
duplicate of https://github.com/livestyle/atom/issues/19

**Comment by sergeche** [comment] 2017-03-09 09:48
Fixed in v0.2.9

**Closed as completed by sergeche** 2017-03-09 09:48 UTC
