### ISSUE TITLE
After upgrade atom to 1.13.0 version emerged some issue

### ISSUE THREAD

**Issue by sanzinken** [livestyle/atom#22] opened 2017-01-21 08:35 UTC
Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

atom-text-editor::shadow livestyle-widget => atom-text-editor.editor livestyle-widget
atom-text-editor::shadow livestyle-widget[position*="top"] => atom-text-editor.editor livestyle-widget[position*="top"]
Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by mstashev** [comment] 2017-03-08 17:34
duplicate of https://github.com/livestyle/atom/issues/19

**Comment by sergeche** [comment] 2017-03-09 09:48
Fixed in v0.2.9

**Closed as completed by sergeche** 2017-03-09 09:48 UTC
